### ISSUE TITLE
Drupal Core Security Update - Highly Critical [1h]

### ISSUE THREAD

**Issue by adamhstewart** [Gizra/ic-conflicts#4]
Per [PSA-2018-001](https://www.drupal.org/psa-2018-001), perform security update as soon as possible after its release on 28 March 2018.

**Comment by ordavidil** [comment]
@IshaDakota - merged 
starting the deploy to 
https://dashboard.pantheon.io/sites/fecefe10-484a-4277-a2b9-3d23f2194af0#dev/code

**Comment by ordavidil** [comment]
@IshaDakota - Live is patched !

**Comment by nedSaf** [comment]
The code in the repo has been updated and the live site as well.
