### ISSUE TITLE
Drupal Core Security Release - Critical

### ISSUE THREAD

**Issue by adamhstewart** [Gizra/ic-conflicts#6]
Per [PSA-2018-003](https://www.drupal.org/psa-2018-003), perform security update as soon as possible after its release on 25 April 2018.

**Comment by ordavidil** [comment]
@IshaDakota 
LIVE has been updated as well:
![toolkit___pantheon_dashboard_](https://user-images.githubusercontent.com/5985683/39263264-8f8f18a0-48b9-11e8-86cf-ce577b7497e4.jpg)
